# Generated by Django 4.1.5 on 2023-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_email_comment_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
